#!/usr/bin/env python3
# coding: utf-8
# SPDX-FileCopyrightText: 2022 KAWAHARA Shuji s21c1036hn@s.chibakoudai.jp
# SPDX-License-Identifier: BSD-2-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    ans += tonum(line)

print(ans)
sys.exit(0)

