#!/usr/bin/env python3
# coding: utf-8
import sys

def tonum(s):
    try:
        return int(s)
    except ValueError:
        return float(s)

ans = 0
for line in sys.stdin:
    ans += tonum(line)

print(ans)

