# test.yaml

name: test  # GitHub Repository の Action Tab で表示される名前
on: push    # Workflow を実行する原因となるイベントを定義（ここでは push されたら実行することになる）
# on: [push, fork] のようにすれば複数のイベントをトリガーにできる
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-latest, macos-10.15, macos-11, macos-12, macos-latest, linux, macos]
                python-version: ["3.7", "3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v3
            - name: All test
              run: ./test.bash
              shell: bash
    soiya:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-latest, macos-10.15, macos-11, macos-12, macos-latest, linux, macos]
        steps:
            - uses: actions/checkout@v3
            - name: Soiya tset
              run: |
                  sudo apt-get install mplayer
                  ./soiya
                  ./soiya -e
              shell: bash
